# playbook.yml
---
- hosts: FR-PA-AD-01
  gather_facts: false
  become: yes
  tasks:
  
  - name: Download file and force basic auth
    get_url:
      url: https://github.com/azwawa/SambaADDC/blob/main/scripts/create_user.yml
      dest: /tmp/create_user_from_ansible.py
      force_basic_auth: yes
  
  - name: Ensure that Samba is running
    ansible.builtin.service:
      name: samba-ad-dc
      tate: started
  
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: /tmp/create_user_from_ansible.py
      dest: /srv/create_user_from_ansible.py
      owner: root
      group: root
      mode: '0700'

  - name: Run a script with arguments (free form)
    ansible.builtin.script: 
      cmd: /srv/create_user_from_ansible.py
